#############################################################
# |  █▀▀█ █   █▀▀█ █  █ █▀▀ █▀▀█  █▀▀█ █▀▀ █▀▀█ █▀▄▀█ █▀▀ | #
# |  █▄▄█ █   █▄▄█ █▄▄█ █▀▀ █▄▄▀  █▄▄█ █▀▀ █▄▄▀ █ ▀ █ ▀▀█ | #
# |  █    ▀▀▀ ▀  ▀ ▄▄▄█ ▀▀▀ ▀ ▀▀  █    ▀▀▀ ▀ ▀▀ ▀   ▀ ▀▀▀ | #
#                  - V. 230407                            | #
#############################################################
# | DO NOT USE THIS FILE FOR ANY OTHER PLUGIN!! | #
###################################################

# The server name that will be displayed in plugin messages.
# Default = [PlayerPerms]
svname: "[PlayerPerms]"

# Perks feature
perks:
    dropHeadOnKill: true
    remoteEnderChest: true
    remoteCrafting: true

# Output the event log.
log:
  isPlayerAfkLog: false

# This is an experimental feature, may contain bugs and is not stable.
experimental:
  bangui: false
  healthbar: false

# This is for debugging. It is not recommended to increase it unless there is a bug.
debug:
  # Shows servers debug info.
  showDebugLog: false
  # Disable CustomRecipe Exceptions, NullPointerException. Please use this feature for only debugging.
  removeRecipeExceptions: false