#############################################################
# |  █▀▀█ █   █▀▀█ █  █ █▀▀ █▀▀█  █▀▀█ █▀▀ █▀▀█ █▀▄▀█ █▀▀ | #
# |  █▄▄█ █   █▄▄█ █▄▄█ █▀▀ █▄▄▀  █▄▄█ █▀▀ █▄▄▀ █ ▀ █ ▀▀█ | #
# |  █    ▀▀▀ ▀  ▀ ▄▄▄█ ▀▀▀ ▀ ▀▀  █    ▀▀▀ ▀ ▀▀ ▀   ▀ ▀▀▀ | #
#                  - FOR FRUIT NET EDITION                | #
#############################################################
# | DO NOT USE THIS FILE FOR ANY OTHER PLUGIN!! | #
###################################################

# This is an experimental feature, may contain bugs and is not stable.
experimental:
  bangui: false