main: com.songro.Main
name: PlayerPerms
version: 1.0
author: notSongro
api-version: 1.19
description: A Simple Friend Plugin (Requires LuckPerms)
depend: [LuckPerms]

commands:
  friend:
    usage: /<command>
    description: 친구목록을 보여줍니다.
    aliases: [fl, ㅊ, 친구, friend]
  join:
    usage: /<command>
    description: 접속 메세지를 변경합니다.
    aliases: [jm, j, ㅈ, 접속]