main: com.songro.Main
name: PlayerPerms
version: 3.20.1
author: notSongro
api-version: 1.19
description: 대부분의 기능을 하나에 플러그인에서

commands:
  #friend:
  #  usage: /<command> (추가/수락/거절/차단)
  #  description: 친구 추가
  #  aliases: [fl, ㅊ, 친구, friend, f]
  playerinfoop:
    usage: /<command> <이름>
    description: 플레이어 정보
    aliases: [po, op정보, pi, plyi]
  targeth:
    usage: /<command> (on/off) <이름>
    description: 해당 플레이어의 체력을 항상 표시해줍니다.
    aliases: [tg, 체력, targethealth]
  playerinfo:
    usage: /<command> <이름>
    description: 해당 플레이어의 정보를 보여줍니다.
    aliases: [p, pi, 정보]
  ban:
    usage: /<command> (normal/ip/list/unban) <이름>
    description: 해당 플레이어를 밴 합니다.
    aliases: [b, 밴, Ban, bn]
  quiet:
    usage: /<command> <이름> <메세지>
    description: 해당 플레이어에게 귓속말을 보냅니다.
    aliases: [q, 귓, ㄱ, qm]
  changename:
    usage: /<command> <바꿀이름>
    description: 채팅 칠때 나오는 이름을 변경합니다.
    aliases: [cn, c, 이름, 이름바꾸기]
  isafk:
    usage: /<command> <이름>
    description: 해당 플레이어가 잠수 모드인지 확인합니다.
    aliases: [ia, 잠수모드, 잠수확인]
  afk:
    usage: /<command>
    description: 잠수모드에 들어갑니다.
    aliases: [잠수, ㅈ, ㅈㅅ, a, afk, af]
  reloadconfig:
    usage: /<command>
    description: 설정을 다시 로드합니다.
    aliases: [r, ㄹ, 리로드, rel, rl]
  # perks
  #remoteanvil:
  #  usage: /<command>
  #  description: 원격으로 모루를 엽니다. (후원 전용)
  #  aliases: [ra, anvil, 모루, 원격모루, ㅁㄹ]
  remoteender:
    usage: /<command>
    description: 원격으로 엔더상자를 엽니다. (후원 전용)
    aliases: [re, ender, 엔더상자, 원격엔더상자, ㅇㅅ]
  remotecrafting:
    usage: /<command>
    description: 원격으로 작업대를 엽니다. (후원 전용)
    aliases: [rc, crafting, 작업대, 원격작업대, ㅇㅈ]
  gpp:
    usage: /<command> <Player> (plus/plusplus/
    description: 해당 플레이어에게 권한을 줍니다.
    aliases: [gp, 권한추가, givepermission]
  homecolor:
    usage: /<command>
  playerattachment:
    usage: /<command>
    description: 특정 플레이어의 권한을 확인합니다.
    aliases: [pa, 권한확인]
  removepermission:
    usage: /<command>
    description: 권한을 제거합니다.
    aliases: [rmp, remove, 권한제거]
  #mute:
  #  usage: /<command>
  #  description: 모든 플레이어 메세지를 못 보내게 합니다.
  #  aliases: [m, mute, 뮤트]
  broadcast:
    usage: /<command> (announce/patch/fix) <Message>
    description: 모든 플레이어에게 공지를 올립니다.
    aliases: [broad, alarm, 알림]
  blocklog:
    usage: /<command>
    description: 보는 방향의 블럭에 대한 로그를 출력합니다.
    aliases: [log, bl, block, 블럭로그, 블럭]
  sit:
    usage: /<command>
    description: 앉습니다.
    aliases: [s, st, 앉기, ㅇㄱ]
  color:
    usage: /<command>
    description: 채팅 색상을 변경합니다.
    aliases: [c, 색상, 채팅색상]

permissons:

  # perks
  perks.*:
    description: 후원 해택
    children:
      perks.normal: true
      perks.plus: false
      perks.pp: false
      perks.ultra: false
      perks.op: op
  perks.normal:
    description: 기본 유저 권한
    default: true
  perks.plus:
    description: 후원 Iron 권한
    default: false
  perks.pp:
    description: 후원 Gold 권한
    default: false
  perks.ultra:
    description: 후원 Diamond 권한
    default: false
  perks.op:
    description: OP 권한
    default: op

  # default
  def.*:
    description: 기본 권한
    def.normal: true
    def.op: op
    def.mutebypass: false
  def.normal:
    description: 기본 유저 권한
    default: true
  def.op:
    description: OP 권한
    default: op
  def.mutebypass:
    description: 뮤트 건너뛰기
    default: false