main: com.songro.Main
name: PlayerPerms
version: 1.0
author: notSongro
api-version: 1.19
description: A Simple Friend Plugin (Requires LuckPerms)
depend: [LuckPerms]

commands:
  friend:
    usage: /<command> (추가) (ㅊ) (add) (거절)
    description: 친구 추가
    aliases: [fl, ㅊ, 친구, friend, f]
  playerinfo:
    usage: /<command> (이름)
    description: 플레이어 정보
    aliases: [p, ㅈ, pi, plyi]